# This is a basic workflow to help you get started with Actions

name: Comunicador de la legion 


on:
  workflow_dispatch:
    inputs:
      villano:
        description: " Que villano envia el mensaje?"
        required: true
        type: choice
        options: 
          - Lex
          - Magneto
          - Jocker
          - Mystique
      
      mensaje:
        description: "Mensaje para el consejo"
        required: true 
        default: "La mision fue un exito"

      prioridad:
        description: " Que nivel de prioridad?"
        required: true
        type: choice
        options: 
          - Bajo
          - Medio
          - Alto
          - Urgente

      cow_message: 
        description: "Tipo de mensaje"
        required: true
        type: choice 
        options: 
          - eyes 
          - cow
          - tongue
jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar transmisor de la legion 
        run: sudo apt-get install -y cowsay
         
      - name: Imprimir variables
        run: | 
          echo "Inputs:"
          echo " ====================== "
          echo "Transmision interceptada"
          echo " ====================== "
          echo ""
          echo "De: ${{ inputs.villano}}"
          echo "prioridad: ${{ inputs.prioridad}}"
          echo "fecha: $( date -u + "%d/%m/%Y - %H:%M UTC" )"
          echo "---------------Mensaje --------------"
          cowsay -f "${{inputs.cow_message}}" "${{ inputs.mensaje}}" 
          echo " ... "

          
