name: Control de calidad

on: 
  push: 
    branches: [ main ]
  pull_request:  
    branches: [ main ]
  
jobs:
  revision-calidad:
    runs-on: ubuntu-latest

    steps:
      - name: Brainaic accede a los planes 
        uses: actions/checkout@v4
      - name: Consejo revisa los cambios 
        # dar privilegio de ejecucion chmod +x  scripts/validar-planes.sh 
        # ejecutar script ./scripts/validar-planes.sh
        run: | 
          chmod +x  scripts/validar-planes.sh 
          ./scripts/validar-planes.sh